### PR TITLE
upgrade biochatter and make modification accordingly

### PR DESCRIPTION
**Pull request by fengsh27**
### Abstract
This submission was to upgrade biochatter to 0.3.13 and made some modification accordingly.

### CODE REVIEW

**Comment by fengsh27** [comment]
@slobentanzer I have updated docker image in docker hub according to current code.

**Comment by slobentanzer** [comment]
@fengsh27 thanks! Could you use the buildx procedure I described in the [README](https://github.com/biocypher/biochatter) for building a multi-arch image in the future?

**Comment by fengsh27** [comment]
@slobentanzer Sure, will do. Thank you for letting me know.

**Review by slobentanzer — APPROVED** [review]
Looks good, thanks!

**Comment by slobentanzer** [comment]
@fengsh27 please also make sure that you bump the version of the biochatter-server to be in line with the docker version.

**Comment by slobentanzer** [comment]
I am doing it for `0.1.3`

**Pull request merged**
