### PR TITLE
[Debug] Without the app.log file, the app.py and the docker will exit

### PR DESCRIPTION
**Pull request by xiaoranzhou**
[Debug] Without the app.log file, the app.py and the docker will exit

### CODE REVIEW

**Comment by slobentanzer** [comment]
@fengsh27 could you please check if this is fine to merge?

**Comment by fengsh27** [comment]
Looks good

**Comment by fengsh27** [comment]
@xiaoranzhou great work! I suggest adding a file called `logs/placeholder` instead of `logs/app.log`. This change will help prevent accidentally committing our own `app.log` to the repo. Additionally, please update `.gitignore` file to include `logs/*.log`.

**Comment by slobentanzer** [comment]
@fengsh27 @xiaoranzhou is this just about keeping the folder, i.e., the actual file is not important? If that is the case, I usually add a `.gitkeep` file, which has the same function as a `placeholder` would have, but is more self-explanatory as well as hidden.

**Comment by fengsh27** [comment]
Yes, I believe it exited due to failing to write `app.log` to folder `./logs`. In this case, `.gitkeep` is a better option.

**Comment by xiaoranzhou** [comment]
As this is under the scope of development, I will close this issue. 😄

**Comment by slobentanzer** [comment]
@xiaoranzhou you also closed the PR, was that your intent?

**Comment by xiaoranzhou** [comment]
Yes, this will be solved by using empty folder and .gitkeep right 😄 ? So I closed it.

**Comment by slobentanzer** [comment]
You also changed some logic in the conversation manager in this PR

**Comment by slobentanzer** [comment]
Also, why not implement the `.gitkeep` solution in this PR and then merge?

**Comment by xiaoranzhou** [comment]
I added this quick and dirty solution to make sure biochatter-server run. 😄 
The wasm was relying the biochatter-server. If biochatter-server does not run, you will not be able to test the wasm part. 
Now I have changed the wasm part to make it independent of the biochatter-server. 
So I will only get back to the biochatter-server, when you finshed the debug.

There are currently also other issues with the port setting the respons format. 
Maybe finish "port" and "respons" first.

**Comment by slobentanzer** [comment]
Agree re the port, we should address #2. What is the response issue? I am not sure I know that one. Can we create an issue?

**Comment by xiaoranzhou** [comment]
https://github.com/biocypher/biochatter-server/issues/6 created, I will add more debug information after the wasm merge finished 😄

**Pull request closed without merging**
